# Generated by Django 3.2 on 2021-05-27 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_entry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='phone number invalid', regex='09(0[1-2]|1[0-9]|3[0-9]|2[0-1])-?[0-9]{3}-?[0-9]{4}')]),
        ),
    ]
